language: node_js

env:
  global:
  - GIT_AUTHOR_EMAIL=bgpat@users.noreply.github.com
  - GIT_AUTHOR_NAME=bgpat
  - GIT_URL=git@github.com:bgpat/pynycode-converter.git
  # DEPLOY_KEY
  - secure: "MEiaSGo1ZzJtdd7bl0TQ26Zy33zJwylC0xkbn2aFwHx29+jyB7tmeCcJzBReRA6RmjN13lV4oUnoJDpQGj/Vw5Ci3ofdrzbkAFf1jXCytzVthbcKScUT3u0ri1cnU2qulCF90n3UoUbq1JSFrka2g2q5oRkhbDZTKnrw6HFTBHT/TBvhdomK8Yi8jjEeU2v3rWbKgHkCHY2Ol3YbZOuRMnWNZb3LFqD7BBDqGpEymxiujz7OgnXncgQ32/LVgnzWB+CP4FqZWEixCd8k0DMYdmGJ4Tp2HkqC9gZRyQw0il2en2D15xApXzZfWTve95/HZDUEzVwRnkF3pCJgOBR+EkLnsNwiKtfDUgwI/bQ9zPTTl0fLuCCITFFdumwx4kxQgiwZq7p8HVF00jxbz+WtkGXJCCRbRVp7FtQxMpTLdmF+4xv5IMBvPC4G61wjmL9rQCR0SedbeG26laEus68oyJdsmWCweVcgV2gxng8IDPqJyi1HdNqbET42BTYw7z3Dbh7KF2IeE58eE3YVKA7mFlJ0rYyr9syWh3hSPfeOEcVDjvaLyR17H1AN/l2EaJBPpJBJeisfnXxP6Hysyg9RJABC+SKPEAiyKDMckFqQy4sfj2gqHw511tgRhVAYQl5KTvbiR5su99askUjavGgczM/s2TVDxZzSGA4icoMfHLM="

install:
- npm install --verbose

before_script:
- rm -rf dist

script:
- npm run build

before_deploy:
- mkdir -p ~/.ssh
- echo $DEPLOY_KEY > ~/.ssh/id_ed25519
- git remote set-url origin ${GIT_URL}
- git fetch origin gh-pages:remotes/origin/gh-pages
- git worktree add -B gh-pages dist origin/gh-pages
- git checkout gh-pages
- git add dist
- git commit -m 'Update gh-pages'

deploy:
  skip_cleanup: true
  provider: script
  script: git push -f
# on:
#   branch: master
