language: node_js
node_js:
- "10"

env:
  global:
  - GIT_AUTHOR_EMAIL=bgpat@users.noreply.github.com
  - GIT_AUTHOR_NAME=bgpat
  - GIT_URL=git@github.com:bgpat/pynycode-converter.git
  # DEPLOY_KEY
  - secure: "fGXC/QTxlPMZT6Omx3sDgSrRIvSOD2t7Kohr4vo2ZrzFBFJ+iDLpiOS9HCUayYeD3dN8IuEPClMhT7ZwkdobkJCcZO9lNOZSJVyxOPhW4IOA6jHxMF2FAgr1DNhasdAAI6tgB84osQnhaup+J9+14Xt3vb0KwQhkLTqNpJZZO+KMYloUP7sYvRfQ/WUgOMDayY0wIHVQcpp6XQbZ4hRrv1yMrsMHpLkQ7kyIhhrYSDtxR24c1vw6GdphREeO6KQyFYunrv9BbilV6f4DNcWA61i2UXZfbyvQOsyUA6tRhLVfzeJnpOha/oug6S+7BXahdNITPWKggmTtP8GlqhWsY93Ok+ETvQZXLjHiFUBxQttv6r4EnDHUjL1ORPGpbYd+h9Pqoe2pqyv9dlljmdEO3yKulrbvNOlCG8qbhx2X5K6PXIgOOa7/coHs12G0mZ/V6YxjqRSJd8b0AMlcQSql9bR9OIl65gpnrlJ6j1DGw0+f4LZaEVnv176I5dRSgXYTTse0X0dpMgxsOZAOxDOjAard3PKFdwlGh6DFGdupkfk8pFOltqmKrKxHFm9FEnBsDOooLUao/WbAvnFO8qiRM3gokvqbFeZCEnMQuVZz2RUqGyST3i58ZxIMW0rbzlj8RNWDcfv/CtUMI39HVP3N+OIGsFxVx8UNd7u+Dn7r7a8="

install:
- npm install

before_script:
- rm -rf dist

script:
- npm run build

before_deploy:
- mkdir -p ~/.ssh
- echo $DEPLOY_KEY > ~/.ssh/id_ed25519
- chmod 600 ~/.ssh/id_ed25519
- git remote set-url origin ${GIT_URL}
- git fetch origin gh-pages:remotes/origin/gh-pages
- git worktree add -B gh-pages dist origin/gh-pages
- git checkout gh-pages
- git add dist
- git commit -m 'Update gh-pages'

deploy:
  skip_cleanup: true
  provider: script
  script: git push -f
  on:
    all_branches: true
# on:
#   branch: master
